### ISSUE TITLE
[editor] Internal server error

### ISSUE THREAD

**Issue by valeriocos** [Bitergia/prosoul#123]
```
prosoul_1         | ERROR:django.request:Internal Server Error: /prosoul/editor
prosoul_1         | Traceback (most recent call last):
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
prosoul_1         |     return self.cursor.execute(sql, params)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/sqlite3/base.py", line 383, in execute
prosoul_1         |     return Database.Cursor.execute(self, query, params)
prosoul_1         | sqlite3.IntegrityError: UNIQUE constraint failed: prosoul_metricdata.id
prosoul_1         | 
prosoul_1         | The above exception was the direct cause of the following exception:
prosoul_1         | 
prosoul_1         | Traceback (most recent call last):
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
prosoul_1         |     response = get_response(request)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 115, in _get_response
prosoul_1         |     response = self.process_exception_by_middleware(e, request)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 113, in _get_response
prosoul_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 71, in view
prosoul_1         |     return self.dispatch(request, *args, **kwargs)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/mixins.py", line 109, in dispatch
prosoul_1         |     return super().dispatch(request, *args, **kwargs)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/mixins.py", line 52, in dispatch
prosoul_1         |     return super().dispatch(request, *args, **kwargs)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 97, in dispatch
prosoul_1         |     return handler(request, *args, **kwargs)
prosoul_1         |   File "/home/prosoul/prosoul/django-prosoul/prosoul/views_editor.py", line 42, in decorator
prosoul_1         |     data = func(*args, **kwargs)
prosoul_1         |   File "/home/prosoul/prosoul/django-prosoul/prosoul/views_editor.py", line 269, in get
prosoul_1         |     get_metrics_data()
prosoul_1         |   File "/home/prosoul/prosoul/django-prosoul/prosoul/views_editor.py", line 761, in get_metrics_data
prosoul_1         |     MetricData.objects.create(id=id, implementation=m)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
prosoul_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 422, in create
prosoul_1         |     obj.save(force_insert=True, using=self.db)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 741, in save
prosoul_1         |     force_update=force_update, update_fields=update_fields)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 779, in save_base
prosoul_1         |     force_update, using, update_fields,
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 870, in _save_table
prosoul_1         |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 908, in _do_insert
prosoul_1         |     using=using, raw=raw)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
prosoul_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1186, in _insert
prosoul_1         |     return query.get_compiler(using=using).execute_sql(return_id)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
prosoul_1         |     cursor.execute(sql, params)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 67, in execute
prosoul_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
prosoul_1         |     return executor(sql, params, many, context)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
prosoul_1         |     return self.cursor.execute(sql, params)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
prosoul_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
prosoul_1         |     return self.cursor.execute(sql, params)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/sqlite3/base.py", line 383, in execute
prosoul_1         |     return Database.Cursor.execute(self, query, params)
prosoul_1         | django.db.utils.IntegrityError: UNIQUE constraint failed: prosoul_metricdata.id
prosoul_1         | [03/May/2019 09:49:58] "GET /prosoul/editor HTTP/1.1" 500 27
```

**Comment by mhow2** [comment]
Looks solved to me.

**Comment by valeriocos** [comment]
Thank you for the feedback @mhow2 !
