### ISSUE TITLE
prosoul_assess fails due to `elasticsearch.exceptions.SSLError`

### ISSUE THREAD

**Issue by valeriocos** [Bitergia/prosoul#133]
This error prevents to calculate the initial qm and populate the corresponding dashboard.

```
elasticsearch_1   | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
prosoul_1         | Traceback (most recent call last):
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 603, in urlopen
prosoul_1         |     chunked=chunked)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 344, in _make_request
prosoul_1         |     self._validate_conn(conn)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 843, in _validate_conn
prosoul_1         |     conn.connect()
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 350, in connect
prosoul_1         |     ssl_context=context)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
prosoul_1         |     return context.wrap_socket(sock, server_hostname=server_hostname)
prosoul_1         |   File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
prosoul_1         |     _context=self)
prosoul_1         |   File "/usr/lib/python3.5/ssl.py", line 760, in __init__
prosoul_1         |     self.do_handshake()
prosoul_1         |   File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
prosoul_1         |     self._sslobj.do_handshake()
prosoul_1         |   File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
prosoul_1         |     self._sslobj.do_handshake()
prosoul_1         | ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)
prosoul_1         | 
prosoul_1         | During handling of the above exception, another exception occurred:
prosoul_1         | 
prosoul_1         | Traceback (most recent call last):
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 220, in perform_request
prosoul_1         |     method, url, body, retries=Retry(False), headers=request_headers, **kw
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 641, in urlopen
prosoul_1         |     _stacktrace=sys.exc_info()[2])
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 344, in increment
prosoul_1         |     raise six.reraise(type(error), error, _stacktrace)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 685, in reraise
prosoul_1         |     raise value.with_traceback(tb)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 603, in urlopen
prosoul_1         |     chunked=chunked)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 344, in _make_request
prosoul_1         |     self._validate_conn(conn)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 843, in _validate_conn
prosoul_1         |     conn.connect()
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 350, in connect
prosoul_1         |     ssl_context=context)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
prosoul_1         |     return context.wrap_socket(sock, server_hostname=server_hostname)
prosoul_1         |   File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
prosoul_1         |     _context=self)
prosoul_1         |   File "/usr/lib/python3.5/ssl.py", line 760, in __init__
prosoul_1         |     self.do_handshake()
prosoul_1         |   File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
prosoul_1         |     self._sslobj.do_handshake()
prosoul_1         |   File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
prosoul_1         |     self._sslobj.do_handshake()
prosoul_1         | urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)
prosoul_1         | 
prosoul_1         | During handling of the above exception, another exception occurred:
prosoul_1         | 
prosoul_1         | Traceback (most recent call last):
prosoul_1         |   File "prosoul/prosoul_assess.py", line 630, in <module>
prosoul_1         |     from_date, to_date, args.attribute)
prosoul_1         |   File "prosoul/prosoul_assess.py", line 487, in assess
prosoul_1         |     publish_assessment(es_url, es_index, assessment)
prosoul_1         |   File "prosoul/prosoul_assess.py", line 432, in publish_assessment
prosoul_1         |     if es_conn.indices.exists(index=scores_index):
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
prosoul_1         |     return func(*args, params=params, **kwargs)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/indices.py", line 273, in exists
prosoul_1         |     return self.transport.perform_request("HEAD", _make_path(index), params=params)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 353, in perform_request
prosoul_1         |     timeout=timeout,
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 229, in perform_request
prosoul_1         |     raise SSLError("N/A", str(e), e)
prosoul_1         | elasticsearch.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720))
oss-app_1         | INFO  [WorkerExecutor] (21:24:32): Worker 'w1' Waiting new Tasks
```

**Comment by valeriocos** [comment]
Fix with: https://github.com/crossminer/scava-deployment/pull/56
