### ISSUE TITLE
Prevent to query the `scava-metrics` index if doesn't exist

### ISSUE THREAD

**Issue by valeriocos** [Bitergia/prosoul#98]
```
prosoul_1         | /usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py:135: UserWarning: Connecting to elasticsearch using SSL with verify_certs=False is insecure.
prosoul_1         |   'Connecting to %s using SSL with verify_certs=False is insecure.' % host)
prosoul_1         | WARNING:elasticsearch:GET https://elasticsearch:9200/scava-metrics/_search?scroll=1m&size=10 [status:404 request:0.747s]
kb-db_1           | 2019-03-28T17:21:57.039+0000    finished restoring CROSSMINER.relation (1420355 documents)
kb-db_1           | 2019-03-28T17:21:57.039+0000    done
prosoul_1         | ERROR:django.request:Internal Server Error: /prosoul/editor
prosoul_1         | Traceback (most recent call last):
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
prosoul_1         |     response = get_response(request)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
prosoul_1         |     response = self.process_exception_by_middleware(e, request)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 124, in _get_response
prosoul_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 68, in view
prosoul_1         |     return self.dispatch(request, *args, **kwargs)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/mixins.py", line 109, in dispatch
prosoul_1         |     return super().dispatch(request, *args, **kwargs)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/mixins.py", line 52, in dispatch
prosoul_1         |     return super().dispatch(request, *args, **kwargs)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 88, in dispatch
prosoul_1         |     return handler(request, *args, **kwargs)
prosoul_1         |   File "/home/prosoul/prosoul/django-prosoul/prosoul/views_editor.py", line 42, in decorator
prosoul_1         |     data = func(*args, **kwargs)
prosoul_1         |   File "/home/prosoul/prosoul/django-prosoul/prosoul/views_editor.py", line 269, in get
prosoul_1         |     get_metrics_data()
prosoul_1         |   File "/home/prosoul/prosoul/django-prosoul/prosoul/views_editor.py", line 728, in get_metrics_data
prosoul_1         |     "match_all": {}
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
prosoul_1         |     return func(*args, params=params, **kwargs)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/__init__.py", line 660, in search
prosoul_1         |     doc_type, '_search'), params=params, body=body)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 318, in perform_request
prosoul_1         |     status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
prosoul_1         |     self._raise_error(response.status, raw_data)
prosoul_1         |   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
prosoul_1         |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
prosoul_1         | elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index')
prosoul_1         | [28/Mar/2019 17:21:57] "GET /prosoul/editor HTTP/1.1" 500 27
```

**Comment by valeriocos** [comment]
Fixed with https://github.com/Bitergia/prosoul/commit/30761977cf281f46c5166785a4380443afe3be41
